//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DelphosEntities : DbContext
    {
        public DelphosEntities()
            : base("name=DelphosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DETALLETRASPASO> DETALLETRASPASO { get; set; }
        public virtual DbSet<TBBODEGA> TBBODEGA { get; set; }
        public virtual DbSet<TBCARGO> TBCARGO { get; set; }
        public virtual DbSet<TBCATEGORIA> TBCATEGORIA { get; set; }
        public virtual DbSet<TBDETALLEOC> TBDETALLEOC { get; set; }
        public virtual DbSet<TBDETALLESTOCK> TBDETALLESTOCK { get; set; }
        public virtual DbSet<TBDETALLEVENTA> TBDETALLEVENTA { get; set; }
        public virtual DbSet<TBMETODODEPAGO> TBMETODODEPAGO { get; set; }
        public virtual DbSet<TBMOVIMIENTO> TBMOVIMIENTO { get; set; }
        public virtual DbSet<TBORDENDECOMPRA> TBORDENDECOMPRA { get; set; }
        public virtual DbSet<TBPROVEEDOR> TBPROVEEDOR { get; set; }
        public virtual DbSet<TBRECEPCION> TBRECEPCION { get; set; }
        public virtual DbSet<TBTRASPASO> TBTRASPASO { get; set; }
        public virtual DbSet<TBUSUARIO> TBUSUARIO { get; set; }
        public virtual DbSet<TBVENTA> TBVENTA { get; set; }
        public virtual DbSet<TBPRODUCTO> TBPRODUCTO { get; set; }
    }
}
