//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCATEGORIA()
        {
            this.TBPRODUCTO = new HashSet<TBPRODUCTO>();
        }
    
        public int IDCATEGORIA { get; set; }
        public string NOMBRE_C { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBPRODUCTO> TBPRODUCTO { get; set; }
    }
}
