//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDETALLEVENTA
    {
        public int IDDETALLEVENTA { get; set; }
        public int IDVENTA { get; set; }
        public int IDPRODUCTO { get; set; }
        public string SKU { get; set; }
        public int CANTIDAD_VENTA { get; set; }
        public int PRECIO_D { get; set; }
        public int SUBTOTAL { get; set; }
        public string METODO_PAGO { get; set; }
        public int IDMETODODEPAGO { get; set; }
    }
}
