//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPROVEEDOR
    {
        public int IDPROVEEDOR { get; set; }
        public string RUT_PRO { get; set; }
        public string NOMBRE_PRO { get; set; }
        public string GIRO { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string EMAIL { get; set; }
        public int TELEFONO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int IDUSUARIO { get; set; }
        public string RUT_U { get; set; }
    }
}
