//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPRODUCTO
    {
        public int IDPRODUCTO { get; set; }
        public string SKU { get; set; }
        public string NOMBRE_P { get; set; }
        public string DESCRIPCION { get; set; }
        public string CATEGORIA_P { get; set; }
        public int PRECIO_P { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int IDCATEGORIA { get; set; }
        public int IDUSUARIO { get; set; }
        public string RUT_U { get; set; }
    
        public virtual TBCATEGORIA TBCATEGORIA { get; set; }
    }
}
