//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBRECEPCION
    {
        public int IDRECEPCION { get; set; }
        public int FACTURA { get; set; }
        public int NORDENCOMPRA_R { get; set; }
        public System.DateTime FECHA_RECEPCION { get; set; }
        public int IDUSUARIO { get; set; }
        public string RUT_U { get; set; }
        public int IDORDENCOMPRA { get; set; }
    }
}
