//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBTRASPASO
    {
        public int IDTRASPASO { get; set; }
        public System.DateTime FECHA_TRASPASO { get; set; }
        public string BODEGA_ORIGEN { get; set; }
        public string BODEGA_DESTINO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
    }
}
