//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUSUARIO
    {
        public int IDUSUARIO { get; set; }
        public string RUT_U { get; set; }
        public string NOMBRE_U { get; set; }
        public string PASSWORD { get; set; }
        public string CARGO_U { get; set; }
        public string STATUS { get; set; }
        public int IDCARGO { get; set; }
    
        public virtual TBCARGO TBCARGO { get; set; }
    }
}
