//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delphos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBVENTA
    {
        public int IDVENTA { get; set; }
        public System.DateTime FECHAVENTA { get; set; }
        public int TOTAL { get; set; }
        public int IDUSUARIO { get; set; }
        public string RUT_U { get; set; }
    }
}
